### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by covert-encryption** [eugene-eeo/monocypher-py#1]
Hi,

This appears to be the better of the two existing Monocypher Python bindings but you haven't done a release since 2020 and there are some Monocypher functions missing that we need to use, although I see you have commits here rather recently. Our tracking issue is https://github.com/covert-encryption/covert/issues/63

I have built a new binding based on this but with a somewhat different design:
- Removing the `crypto_` prefix of all functions
- Implementing a custom Python buffer type that automatically wipes its contents on deletion
- Returning that type, or optionally using any existing bytes-like writable buffer for return values
- Adding docstrings

The new implementation is based on your CFFI build and I'd wish to have it released on PyPi but would prefer not to add a third option there, and would also prefer not to keep maintaining it long term. So, I could either make a fork of this project, replace the Python implementation and release under another module name such as `monocyph` to avoid conflicts, or ideally you could adapt the new code (a breaking change obviously but given the version number is still 0.0.1 I gather that this might not be too bad). I could make a PR here if you wish to review it closer.

There are a few remaining issues such as using hashlib sha512 as a custom hash for Monocypher which itself only implements Blake2b, making it incompatible with standard Ed25519 keys and signatures. I am not sure whether @LoupVaillant intends to add a C implementation of SHA-512 to allow standards compatibility.

Let me know of your thoughts and intentions on this.

**Comment by LoupVaillant** [comment]
> I am not sure whether @LoupVaillant intends to add a C implementation of SHA-512 to allow standards compatibility.

Monocypher already has an implementation of SHA-512 in its [optional files](https://github.com/LoupVaillant/Monocypher/tree/master/src/optional). I needed it for Ed25519 to begin with, so I exposed it to the end user, and added HMAC to give it feature parity with Blake2b.

Note that the makefile provides a way to bundle both the main compilation unit and the optional compilation unit in the same shared library, so language bindings that want to rely on both, can.

**Comment by covert-encryption** [comment]
@LoupVaillant Cool, then just need to add the optional files to the build (very simply done in Python CFFI by setuptools during package build, not using the Makefile) and implement wrappers for those functions as well. This is much better, as it avoids building vtables and supporting the generic functions in Python.

**Comment by eugene-eeo** [comment]
Hey there, apologies for the late response.

The library is (from my point of view) feature-complete since I don't plan to use the SHA256 features that you are requesting (which indeed, can be included by including the optional files in Monocypher). I'm actively using it for a small tool I have locally.

Couple of notes:
 - I initially used `crypto_` prefix against all of the functions, so that I could easily find documentation for them in the Monocypher manual.
 - Yep -- that buffer bit did irk me a little, glad that you found a custom solution.
 - And yes, docstrings are lacking because the expecatation was that mainly users would use the higher level API, and if you're using the lower-level API they would map 1-1 with Monocypher's manual.

I'm more than happy to review your PR.

**Comment by covert-encryption** [comment]
#2 adds the optional module but does no other changes and provides no high level wrapper. Feel free to make one, or change the current one to use standard Ed25519 instead (I find very little use for the non-standard implementation that uses Blake2b).

The other changes are more breaking, and will have to be done as separate PRs, if not as a separate module built on this.
